version: "3.7"
services:
  web:
    build: app
    ports:
      - 80:80
  db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: polivel@12
      MSSQL_PID: Development
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu

